# Generated by Django 5.2 on 2025-04-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
    ]
