# Generated by Django 5.2 on 2025-06-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='blogs/thumbnails/'),
            preserve_default=False,
        ),
    ]
