# Generated by Django 5.2 on 2025-04-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_data_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=21, verbose_name='شماره تلفن')),
                ('title', models.CharField(max_length=255, verbose_name='موضوع')),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('1', 'Very Urgent'), ('2', 'Urgent'), ('3', 'Medium'), ('4', 'Low')], max_length=20, verbose_name='اولویت')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
