# Generated by Django 5.2 on 2025-04-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='priority',
            field=models.CharField(choices=[('1', 'بسیار فوری'), ('2', 'فوری'), ('3', 'متوسط'), ('4', 'پایین')], max_length=20, verbose_name='اولویت'),
        ),
    ]
