# Generated by Django 5.2 on 2025-05-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_contactus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'نویسنده'), ('NORMAL', 'عادی')], default='NORMAL', max_length=20),
        ),
    ]
